### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by grindhold** [nmelnick/gredis#3]
This library is missing a license. I'd suggest opting for LGPLv3 to guarantee freedom and a broad range of possible applications.

**Comment by nmelnick** [comment]
Good catch. I have generally opted for the Apache 2.0 license, as it guarantees freedoms while also not restricting commercial usage.

**Comment by grindhold** [comment]
Yes, this would also nice. I am always a bit shy contributing to projects that have no license sticking to it because I do not really know what I may use the code for. Now that this is settled you can expect me to deliver sortedset operations in the next weeks.

**Comment by nmelnick** [comment]
License claimed in b412294.
