### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by grindhold** [nmelnick/gredis#5]
gredis loves exploding when used in multithreaded environments.
a possible solution is provided in #4 . if you see any other choice to lock the context without breaking your design, feel free to do so.
[opened the issue, for the sake of documentation in case my PR gets rejected]

**Comment by nmelnick** [comment]
Thank you for the contribution -- and sorry it took me so long. This looks great so far, I merged it as I'm happy to see it in there, and may enhance later.
